Output demo-rm.gif

Set FontSize 20
Set Width 900
Set Height 500

Type "ssh -p 2222 anyone@localhost"
Enter

Sleep 900ms

Enter

Sleep 700ms

Type "rm -rf /"
Enter

Sleep 2500ms

Type "ls"
Enter

Sleep 900ms

Type "whoami"
Enter

Sleep 900ms

Type "echo still technically alive"
Enter

Sleep 1200ms

Type "exit"
Enter

Sleep 900ms

Type "ssh -p 2222 anyone@localhost"
Enter

Sleep 900ms

Enter

Sleep 700ms

Type "ls"
Enter

Sleep 1400ms

Type "exit"
Enter

Sleep 900ms
