Output demo-pty.gif

Set FontSize 20
Set Width 900
Set Height 500

Type "ssh -p 2222 anyone@localhost"
Enter

Sleep 900ms

Enter

Sleep 700ms

Type "echo real pty support"
Enter

Sleep 700ms

Up

Sleep 500ms

Enter

Sleep 900ms

Type "vi proof.txt"
Enter

Sleep 800ms

Type "inot possible over a raw pipe"
Escape

Sleep 500ms

Type ":wq"
Enter

Sleep 800ms

Type "cat proof.txt"
Enter

Sleep 1400ms

Type "exit"
Enter

Sleep 900ms
